services:
  db:
    container_name: brevly-server-db
    image: bitnami/postgresql:17.4.0
    restart: always
    environment:
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASSWORD
      - POSTGRESQL_DATABASE=$POSTGRESQL_DATABASE
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - data:/bitnami/postgresql
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
    - brevly-net
    - db
  
  app:
    container_name: brevly-server-app
    build:
      context: .
      target: development
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    restart: always
    ports:
      - 3000:3333
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - brevly-net

volumes:
  data:
networks:
  brevly-net:
    driver: bridge
  db:
    driver: bridge